name = "iflow-openai"
main = "worker.js"
compatibility_date = "2026-02-05"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "IFLOW_KV"
id = "9046f1f395944e738439477f248a145e"

# 定时任务：每24小时自动更新模型列表（Cron 表达式）
[triggers]
crons = ["0 0 * * *"]